### ISSUE TITLE
Deleting items from clipboard

### ISSUE THREAD

**Issue by OmarShawky1** [friday/ulauncher-clipboard#31] opened 2021-12-01 13:39 UTC
**Describe the solution you'd like**
A simple option whereby i can press `del` to delete an entry.

**Comment by friday** [comment] 2022-03-04 05:28
Duplicate of #5, and also not quite possible to implement this way (extensions can use "enter" or "alt+enter).

Although I think it would be cool if Ulauncher had the option to use the delete key it's not high on the list since it's never been requested before.

**Closed by friday** 2022-03-04 05:28 UTC
